DATABASE = "articles"
USER = "postgres"
PASSWORD = "password"
HOST = "localhost"
PORT = "5432"
URL = "https://www.researchgate.net/publication/220591356_Identifying_Software_Project_Risks_An_International_Delphi_Study"
